apiVersion: v1
kind: Namespace
metadata:
  name: serpiente
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dpy
  namespace: serpiente  
spec:
  selector:
    matchLabels:
      app: matchlabel-world 
      #coinside con selector en service
  replicas: 2
  template:
    metadata:
      labels:
        app: matchlabel-world
        #coinside con selector en service
    spec:
      containers:
      - name: hello-world
        image: bhargavshah86/kube-test:v0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-srv
  namespace: serpiente  
spec:
  selector:
    app: matchlabel-world
    #coinside con selector en deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082   
  type: NodePort
